variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"


pytest:
    cache:
        paths:
          - "$CI_PROJECT_DIR/pip-cache"
        key: "$CI_PROJECT_ID"
    image: python:3.8
    stage: test
    variables:
      PYTHONPATH: ./
    script:
        - pip install -U setuptools pbr
        - pip install -r requirements-dev.txt
        - pip install -e .
        - LOGLEVEL=info py.test --cov squidreport --cov-report term-missing --tb=native

linter:
    cache:
        paths:
          - "$CI_PROJECT_DIR/pip-cache"
        key: "$CI_PROJECT_ID"
    image: python:3.8
    stage: test
    variables:
      PYTHONPATH: ./
    script:
        - pip install pre-commit
        - pre-commit run --all-files
